### PR TITLE
Fix t bin for the TOF exponential distribution 

### PR DESCRIPTION
**Pull request by carmenromo**
In the old version of the function `convolve_tof` there was a small bug introducing a difference of one bin in the t bin for the `tof_response` table. This bug has been solved and a tests has been included to check that the first time bin for every sensor remains the same after applying the exponential distribution.

### CODE REVIEW

**Comment by paolafer** [comment]
I find nothing wrong in the code, but I don't know the details of the original code by @viherbos. Vicente, could you give a look at the code and tell us the reason of the previous implementation of the `convolve_tof` function? Do you agree with the fix?

**Comment by viherbos** [comment]
By definition the convolution operation has N+M-1 samples, where N and M are the pe vector and the SiPM response vector...
I have not checked the tests but maybe the bug is elsewhere

**Comment by paolafer** [comment]
I agree with you, Vicente. In the simplest case where the SiPM has dimension 1, the result of convolution must be exactly N, not N+1. 
Is it correct to expect that the bin of the first photoelectron in the case of 0 threshold should be the same as if we don't use convolution at all?

**Comment by carmenromo** [comment]
> By definition the convolution operation has N+M-1 samples

Oh, this I didn't know, this is why in the last version I deleted the "-1"

**Comment by paolafer** [comment]
I think that the "problem" is that the double exponential function has a value of `0` in the first bin, so whatever the signal to be convoluted, it will always have 0 in the first bin, hence the difference of 1 bin. @viherbos, is that correct? Should we model the double exponential function in such a way that the first bin is not zero?

**Comment by viherbos** [comment]
Asuming a very small timebin... Does it make any difference?
In case it is need, I guess we could simply discard the first sample of the double exponential

**Comment by paolafer** [comment]
> Asuming a very small timebin... Does it make any difference?
> In case it is need, I guess we could simply discard the first sample of the double exponential

I was rather thinking about keeping the functions as they are and, when we use them, using the central value of each bin instead of the left edge, so that no zero time appears.
For instance, to apply the convolution, right now we are defining an array of times such as `[0, 5, 10, ... ]`. We could use `[2.5, 5.5, 12.5, ...]` instead, and that would remove the problem. In fact, I think that it is also more accurate, don't you think?

**Comment by viherbos** [comment]
Yes. It makes sense. However I think that in the end we would get something similar since this is equivalent to a half-bin timeshift

**Comment by paolafer** [comment]
Yes, I don't think it has any impact at all on the results, but I would like to use it in the most correct way.

**Comment by paolafer** [comment]
@carmenromo, I would then close this PR and I'll add this modification to the one of the reconstruction script, if you're ok with that.

**Comment by carmenromo** [comment]
Sure. It's ok with me

**Pull request closed without merging**
